[package]
name = "rustlin"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "os",
    "os/bootloader",
    "os/kernel",
    "cargo",
]

[dependencies]
os = {path = "os"}
anyhow = "1.0.13"
