[package]
name = "bootloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "amd64-bios"
test = false

[[bin]]
name = "amd64-uefi"
test = false

[dependencies]
hw = {path = "../hw"}
